# Generated by Django 4.2.4 on 2023-08-14 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Woj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nazwa')),
                ('symbol', models.PositiveSmallIntegerField(verbose_name='Numer Województwa')),
                ('update_date', models.DateField(verbose_name='Stan na')),
            ],
            options={
                'verbose_name': 'Województwo',
                'verbose_name_plural': 'Województwa',
            },
        ),
        migrations.CreateModel(
            name='Pow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa')),
                ('symbol', models.PositiveSmallIntegerField(verbose_name='Numer Powiatu')),
                ('update_date', models.DateField(verbose_name='Stan na')),
                ('rodz_powiat', models.CharField(choices=[(1, 'powiat'), (2, 'miasto na prawach powiatu'), (3, 'miasto stołeczne, na prawach powiatu')], max_length=1, verbose_name='Rodzaj powiatu')),
                ('woj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='powiaty', to='PodzialPolski.woj')),
            ],
            options={
                'verbose_name': 'Powiat',
                'verbose_name_plural': 'Powiaty',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Gmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa')),
                ('symbol', models.PositiveSmallIntegerField(verbose_name='Numer Gminy')),
                ('update_date', models.DateField(verbose_name='Stan na')),
                ('rodz_gminy', models.CharField(choices=[(1, 'gmina miejska'), (2, 'gmina wiejska'), (3, 'gmina miejsko-wiejska'), (4, 'gmina miejska, miasto stołeczne')], max_length=1, verbose_name='Rodzaj Gminy')),
                ('powiat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gminy', to='PodzialPolski.pow')),
            ],
            options={
                'verbose_name': 'Gmina',
                'verbose_name_plural': 'Gminy',
            },
        ),
    ]
